# Generated by Django 3.1.7 on 2021-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210306_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='total_hits',
            field=models.IntegerField(default=0),
        ),
    ]
